name: Tailscale SSH Session

on:
  workflow_dispatch:

jobs:
  ssh:
    name: Start SSH Session
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ssh: true

      - name: Keep alive
        run: echo "SSH session is active. Press Ctrl+C in your local terminal to disconnect." && tail -f /dev/null
